[package]
edition = "2021"
name = "xtask"
publish = false
version = "0.0.0"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.71"
duct = "0.13.6"
probe-rs = "0.18.0"
probe-rs-cli-util = "0.18.0"
